### ISSUE TITLE
Extend record and filter for ACK messages

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#10]
The record should be extended so that it is possible to filter for ACK messages.

**Comment by croser** [comment]
backend: filter and record to be extended, no ACK messages in getTimelineRecords
frontend: add filter to list

**Comment by thoobr** [comment]
msgType is provided in record.
possible values:
Info
Warn
Error
Ack

**Comment by croser** [comment]
Assumption:
- Possible message types are hard-coded and (other than other filter options) not retrieved from backend.
