### ISSUE TITLE
Display GeoInformation in map

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#20]
If the message contains geographical information (CAP, GeoJson) this should be displayed on a minimap.

**Comment by croser** [comment]
For CAP see eu.driver.model.cap

**Comment by croser** [comment]
Display of GeoJSON for GeoJSONEnvelope done.

For CAP, i need more specifications & sample data: From where can i obtain geo information in which format? Ideally we retrieve GeoJSON - everything else might be significantly more work.

**Comment by thoobr** [comment]
CAP is done.
