### ISSUE TITLE
Map display für Cap Alert Messages

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/after-action-review#24]
Background:

* Alert has list of info objects, each info has list of areas, each area is either polygon (closed list of points) or circle (lat, lon, radius - 0 if point)
* Points are WGS84

Tasks:

* Render geometries
  * Polygon
  * Circle
  * Point
* Use styling from geocode, valueName = "style" - should be openlayers styling

Example data: 

* ClientID = socrates

**Comment by croser** [comment]
Done.
@thoobr: Can you please test, in particular for "circles" - i did not find any samples for that when skimming through data, plus i dont know about the unit that is used for "radius". Let's see if openlayers does it correctly.

**Comment by thoobr** [comment]
Basically the circles are working, I need to check the radius.
But I found one error, i the info object as not area then the client throws an error to the console that null is not iterable.

**Comment by croser** [comment]
Handled null.
And also the (kind of weird) aspect that area can be either directly an object or an object array. @thoobr: Is this intended?

**Comment by thoobr** [comment]
Yes, I can happend that the area is only one object or an array of objects.
