### ISSUE TITLE
Update timeline upon session management message

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/after-action-review#27]
A session management message updates sessions.
No new bar is displayed upon arrival in the timeline.
Expected: With a session management message reload timelime.

**Comment by thoobr** [comment]
A Swagger function is now available to test this.
![image](https://user-images.githubusercontent.com/16935688/68656364-f890d880-0531-11ea-885f-0a8f35c709d6.png)

You can always need to test START/STOP message top see the bar starting and ending.
