### ISSUE TITLE
create Reports menu

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#28]
For creating the different kind of reports we need a new Menu "Reports" with following submenu items:
* FirstImpressionEvaluation
* BaselineObservation
* Innovationline Observation
* Observations

for FirstImpressionEvaluation following endpoint is available:
HTTP GET: /AARService/createFIEPDFReport
for all others use: 
HTTP GET: /AARService/createPDFStatisticReport

The result is in both requests a PDF file that should be dispalyed and possible to be stored on the local client hard disk

**Comment by croser** [comment]
Done. However, createFIEPDFReport is not (yet) available on develop.

**Comment by thoobr** [comment]
I have forgotten to mention here one thing:
for PDF Reports (not the FIE, Observsations) you need to pass a query parameter:

Baselinereport: ?runType=Baseline
Innovationline Observation: ?runType=Innovationline

And out of a discussion we need 2 additional menu entries:
TrialDimensionreport: ?runType=TrialDimension
SolutionDimension: ?runType=SolutionDimension
