### ISSUE TITLE
Filter does not work in development environment

### ISSUE THREAD

**Issue by croser** [DRIVER-EU/after-action-review#32]
It seems that filtering does not work in development environment with two hosts localhost:8080 and localhost:8095.

A reason for this might be that each request arrives on the server with a different session id. Axios/fetch must be told to send cookies explicitly.

**Comment by croser** [comment]
This was a tricky one.

@thoobr: I had to adapt the SimpleCORSFilter on server-side too. Please review if you are okay with the changes.

**Comment by thoobr** [comment]
working again
