### ISSUE TITLE
Display WMS Layer in MapLayerUpdate msg

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#39]
When the MapLayerUpdate message layerType = WMS
Display the layer on the map:
the URL in the message points to a server and the title is the layer name.
ExamlleMessage:
{"url": "http://91.237.80.240/erdas-iws/ogc/wms/GOPR_data", "title": "GOPR-SW_20190909130902.tif", "description": "50.5630133422495,19.5153603424183,50.55449072493898,19.52725677227046", "username": "null", "password": "null", "updateType": "CREATE", "layerType": "WMS"}

**Comment by croser** [comment]
@thoobr: Please clarify: 

On which map shall this layer be displayed?
Only on the currently open map?
What if no map is open?
What shall happen when the user navigates away to another detail view?

**Comment by thoobr** [comment]
display it in the default map that we also use for CAP/GeoJSON...
OSM basemap and wms layer as overlay
then not map is displayed
in the description you can find the BBox of the layer, add a center button and navigate to the BBOX (open layers zoomToExtend)

**Comment by croser** [comment]
done, based on the following assumptions:

* when navigating away from the details view, the previously received WMS layer gets discarded
* only when a new WMS layer message comes in while the details view is open, we add it to the map
* the server wraps MapLayerUpdate in (also committed) WSMapLayerUpdate

ok?

**Comment by thoobr** [comment]
display the WMS layer only when the corresponding message (details) are opened.

**Comment by croser** [comment]
@thoobr : what does "corresponding" message details mean?

**Comment by croser** [comment]
This ticket is more about displaying a map for the message type "MapLayerUpdate".
