### ISSUE TITLE
Add specific details views

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#5]
We need specific details views for:
RolePlayerMessage
SessionMessage
PhaseMessage
ObserverAnswer

**Comment by croser** [comment]
please provide specification for each view

**Comment by thoobr** [comment]
**For the observerToolAnswer:**

- RecordID (from the record)

and from the jsonObject:

- timeSendUTC
- observationTypeName

from the array of Questions

- name
- answer

**Comment by thoobr** [comment]
**For the RolePlayerMessage**

From the Reocrd:
- RecordID

and from the jsonObject:
- type
- title
- headline
- description
- rolePlayerName

**Comment by thoobr** [comment]
**For the RolePlayerMessage**

From the Reocrd:
- RecordID

and from the jsonObject:
- trialName
- scenarioName
- sessionName
- sessionState

**Comment by thoobr** [comment]
For the PhaseMessage

From the Reocrd:
- RecordID

and from the jsonObject:
- phase
- isStarting

**Comment by thoobr** [comment]
In all details view, still the json should be displayed at the end of the view

**Comment by croser** [comment]
Assumptions:

- ObserverToolAnswer.timeSendUTC in epoch millis
