### ISSUE TITLE
Display attachements from recored

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#6]
In the Reocrd also attachements should be displayed.
A click on the attachement opens the file in a popup window.

**Comment by croser** [comment]
display a list of URLs in detail view, for each message type

**Comment by croser** [comment]
waiting for backend

**Comment by thoobr** [comment]
Backend in develop ready. Record object has a list of attachements.

**Comment by croser** [comment]
Please consider:

* typo in "attachements"
* assumption: in attachment.name we have a link starting with http[s]:// that is listed as clickable

**Comment by thoobr** [comment]
typo in attachments corrected

**Comment by thoobr** [comment]
Working
