### ISSUE TITLE
links in sequence diagrams

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/after-action-review#8]
It should be possible to click on a message in the sequence diagram to view the details of the record. This is only possible if image is changed to SVG.

**Comment by croser** [comment]
SVG shall contain links to a specific (new) detail page

**Comment by thoobr** [comment]
SVG contains links to the details page.

**Comment by croser** [comment]
hmm, please clarify: the SVG now contains links to /details.html - where is this details.html expected to be provided from? it is not there in our web application. what shall be shown when a link is clicked?

**Comment by thoobr** [comment]
basically, the same information as in the main page in the right side panel when we select a record.
Maybe it would be better not to show this in a separate page, but show the information in an popover. Would this work, if yes, do we need to change the link?

**Comment by croser** [comment]
No, i guess i can handle that. Thanks for clarification.
